version: '3.8'

services:
  # Serviço da aplicação Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-filtros-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
    depends_on:
      - mysql
      - redis

  # Servidor web Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel-filtros-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: laravel-filtros-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_filtros
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: laravel-filtros-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel-network

  # PhpMyAdmin (opcional para desenvolvimento)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-filtros-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - laravel-network
    depends_on:
      - mysql

# Volumes para persistência de dados
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

# Rede para comunicação entre containers
networks:
  laravel-network:
    driver: bridge